export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST'
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL'

export const BLOG_ITEM_REQUEST = 'BLOG_ITEM_REQUEST'
export const BLOG_ITEM_SUCCESS = 'BLOG_ITEM_SUCCESS'
export const BLOG_ITEM_FAIL = 'BLOG_ITEM_FAIL'

export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST'
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS'
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL'

export const BLOG_EDIT_REQUEST = 'BLOG_EDIT_REQUEST'
export const BLOG_EDIT_SUCCESS = 'BLOG_EDIT_SUCCESS'
export const BLOG_EDIT_FAIL = 'BLOG_EDIT_FAIL'

export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST'
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS'
export const BLOG_DELETE_FAIL = 'BLOG_DELETE_FAIL'

export const BLOG_USER_REQUEST = 'BLOG_USER_REQUEST'
export const BLOG_USER_SUCCESS = 'BLOG_USER_SUCCESS'
export const BLOG_USER_FAIL = 'BLOG_USER_FAIL'
